### ISSUE TITLE
Persist legend selection in short URLs

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#281]
Use case:
I want to send a link to a graph with the same legend settings I'm looking at, e.g. to highlight a 5xx response rate which would be barely visible otherwise.

**Comment by stuartnelson3** [comment]
Can you clarify whether this is a link to a single widget, a dashboard with all the settings serialized into the URL, or both?

I'm guessing that in order to do this we would have to copy the legend selection data, which we're currently storing somewhat ethereally in memory during a redraw, to the graph data data-structure. if you want this functionality on a single widget page, it will definitely have to be persisted in the dashboard's JSON blob, and if you want it to be encoded in a URL, I could probably append it as data to each graph widget.

@grobie is this enough of a feature to warrant the additional code complexity, or would it be saving you clicking 1-3 legend items a couple times a day?

@juliusv thoughts?

**Comment by juliusv** [comment]
Yeah, should be as straightforward as storing the legend state in the graph's settings instead of in an ephemeral local variable. Ok from my side, unless I overlooked something and it gets too complicated in the details.

**Comment by stuartnelson3** [comment]
the only issue I can foresee is if the user saves after making this change. we'll have to update the JSON schema to include this new information. i assume this is ok?

**Comment by juliusv** [comment]
Ok, I assumed that was what grobie wanted anyways, but maybe he was only talking about the single-widget graph link view. Guess I'm fine with doing it as I suggested though...

**Comment by grobie** [comment]
I was only thinking about the single widget graphs **. I don't mind if it's possible to persist them in dashboards to, but I don't have a use case for this right now.

** I'm confused by the terminology in promdash, judging by the table name, I thought you name these "Short URLs"?

**Comment by stuartnelson3** [comment]
closed by #291
