### ISSUE TITLE
Stacked graphs show wrong Y-axis scale

### ISSUE THREAD

**Issue by juliusv** [prometheus/promdash#327]
When stacking a graph, the Y-axis scale remains at the unstacked scale:

![stacked_scale_bug](https://cloud.githubusercontent.com/assets/538008/6091913/efffc5f6-aec3-11e4-8d99-1f13af56f92c.png)

**Comment by stuartnelson3** [comment]
unstacked
![image](https://cloud.githubusercontent.com/assets/1398104/6092561/ded29fbc-aee4-11e4-960c-1de0c1a8318a.png)
to stacked
![image](https://cloud.githubusercontent.com/assets/1398104/6092562/f6bd115c-aee4-11e4-9b08-a63c252cd487.png)

let's have a look at this on monday, because the behavior seems to be working for me (if i understand the description of the bug correctly)

**Comment by juliusv** [comment]
I was stupid - closing :D

**Comment by stuartnelson3** [comment]
* screenshot captured *
