### ISSUE TITLE
Add ability to specify `serverURL` or `serverID` as URL parameter

### ISSUE THREAD

**Issue by mwitkow-io** [prometheus/promdash#362]
We have multiple clusters running, with a similar environment running in every one of them, each having its own Prometheus.

We would like to use the same dashboards to view different datacenters, by parametrising which Prometheus to connect to.

Basically it's an ability to specify `serverURL` or `serverID` on the URL parameter.

**Comment by matthiasr** [comment]
Seconded! This would save us from cloning a bunch of dashboards every time too.

I'm wondering how to reconcile this with dashboards that use more than one server. Maybe a generic solution would be to allow template variables in server names …

**Comment by juliusv** [comment]
This is similar/ to / the same as https://github.com/prometheus/promdash/issues/180.

:+1: in spirit, but needs a better idea for implementing this.

Simply setting a `serverURL`/`serverID` would not help in many use cases, because a dashboard (and even a single graph) often use more than a single server in each zone. For example, our service dashboards for each zone use their own service Prometheus for their service-specific metrics in that zone, while also pulling in metrics from the Prometheus that has routing/traffic metrics for each service in that zone, and also displaying Bazooka resource usage stats from the Prometheus that has Bazooka metrics. They all need to be parametrized by their zone somehow, within a single dashboard.

Closing this issue in favor of https://github.com/prometheus/promdash/issues/180.
