### ISSUE TITLE
Dashboard templates

### ISSUE THREAD

**Issue by grobie** [prometheus/promdash#375]
With #373 being merged, it's now easily possible to use the same graphs (server + expressions) in different dashboards by setting different template variables. In order to create a new dashboard, one only needs to clone such dashboard, set a new template variable and save, which is simple enough.

The problem comes if one needs/wants to change the dashboard. After making changes in one dashboard, the other instances need to be deleted, cloned again, etc. Alternatively, all changes need to be applied manually to each instance of dashboard used with different template variable sets.

One way to make that easier could be to introduce different types of dashboards:
* **dashboard standalone** (what we have right now)
* **dashboard template** (can't be used directly without template variables)
* **dashboard profile** (links to to dashboard template and defines all required variables)

~~In the dashboard list, dashboard templates would be hidden or only shown in a separate tab.~~ (maybe, still in discussion). In the view of of dashboard profile, we could then show a list of alternative profiles linking to the same template as dropdown menu.

An additional confirmation should be shown probably if someone tries to update a dashboard profile, explaining that the change will effect the template and all other profiles as well. Alternatively, the save button gets removed in profiles, or replaced with a link to the template view.

This would solve the rest of #180.

What do you think? @juliusv @stuartnelson3 @matthiasr

**Comment by stuartnelson3** [comment]
>An additional confirmation should be shown probably if someone tries to update a dashboard profile, explaining that the change will effect the template and all other profiles as well.

Changes to a profile won't have any affect (IMO). It is just a json blob:

```json
{
  var1: "val1",
  var2: "val2",
  var3: "val3"
}
```

The template defines a list of keys, in addition to all the widgets and settings it stores. A profile must have values for all of these keys.

A change to a template would render an alert saying "this list of profiles will be affected and must be updated".

`templates#new` and `templates#edit` are like `dashboards#new` and `dashboards#edit`, but with an arbitrary amount of key-value inputs. If a value is entered for a particular key, that becomes the default value when creating a profile for that template.

`profiles#new` and `profiles#edit` are just pages displaying a key-value list. Keys are static (defined in the template), and **all values must be entered**. the user selects a template from a dropdown of all templates, which then renders out the variables defined for that template, and all other profiles currently using it.

I'm thinking about two ways of managing this:

1. `/profile/:slug`: renders a profile against its associated template. profile variables can't be added or removed, but they can be modified (and then saved).
  - how much do we want profiles to be configurable? e.g. endTime, range, etc? Should these values be taken from the template?
2. `/template/:slug#?profile=someProfile`
  - this might be something nice to support on a template page, so that you can see changes quickly to your template as they would affect a profile, but adding links to these would be silly and probably unnecessarily messy.

Questions:

1. Would profiles be added to directories, and therefore be visible on the main page side-by-side with normal standalone dashboards?
2. I mention above that all key-value pairs defining a template must be filled in for a profile. Do we want this? Or do we want users to be able to leave values blank?
3. Do we want to require a default value for every key-value pair in a template?

**Comment by grobie** [comment]
Hm, let's sync first on this, I don't understand all of the comments yet.

**Comment by stuartnelson3** [comment]
it's evolving. i'm already ditched the routes stuff i mentioned above. wip is here https://github.com/prometheus/promdash/pull/377

**Comment by grobie** [comment]
What we've discussed so far:

* Templates and standalone dashboards are almost identical, we still want to separate them so far to make the UI and handling more explicit. Users will get a select/dropdown option to choose the dashboard type. If viewing a template dashboard (still at http://promdash/:slug), some clear UI indicator will tell that.
* Profiles are sets of template variables and a reference to a template dashboard. A profile can only be attached to a single template. Profiles will be located at `http://promdash/:dashboard/:profile`. For example a template `awesomeapp` with two profiles `staging` and `production` will result in a URL like `http://promdash/awesomeapp/production`.
* An additional dropdown element will be added to template and profile views, in order to switch between profiles.
* The dashboards list will show all available profiles for a template.

**Comment by grobie** [comment]
An idea to manage profiles: Instead of a new list view of templates, profiles could just be managed in the template view. If looking at a template, we could add a box above the graphs for the profiles, with tabs for the different profiles, a plus button to create a new profile and crosses to delete templates.

As a nice side effect, that should also already make pretty clear that one views a template.

**Comment by grobie** [comment]
After more discussions, we'll do it even simpler:

* no more distinction in standalone/template dashboards
* profiles will be saved as part of a dashboard
* All the creation/manipulation of profiles will happen on the dashboard page

**Comment by grobie** [comment]
- current template variables stay as they are and become basically the "general variables" which always apply
- new profiles can optionally be added. by default, no profiles are available
- if any profile is available, we'll always redirect the dashboard to /:slug/:profile
- variables set in profiles win over variables set in general
- if there are more than one profile, than the user can switch between them while editing. one of them is always selected. any changes to the currently selected profile get replicated to all other profiles. So deleting a variable from the currently selected profile form  will cause the same variable to be deleted in all other profiles as well. similar for adding new variables.

@stuartnelson3
