### ISSUE TITLE
Setting PROMDASH_PATH_PREFIX does not work for assets

### ISSUE THREAD

**Issue by mingfang** [prometheus/promdash#434]
When I set PROMDASH_PATH_PREFIX, eg ```promdash```, the dashboard comes up but all the assets are broken.

I don't know Ruby but I was able to hack it to work by removing line 40 from https://github.com/prometheus/promdash/blob/master/config/application.rb

**Comment by juliusv** [comment]
So it also doesn't work for me. The assets are served under the correct prefix, but the links to them are generated without the prefix. Even links that are clearly generated through Rails helpers are wrong: `asset_path('graph_template.html')` in https://github.com/prometheus/promdash/blob/master/app/assets/javascripts/angular/directives/graph.js.erb#L11.

I found http://serverfault.com/questions/638905/does-rails-4-asset-path-helper-uses-asset-prefix. Regarding the example I mentioned above, the actual graph HTML template file has an `.html.erb` extension instead of just `.html`. Referring to just `.html` works without a path prefix, but breaks when setting one. Adding the missing `.erb` unbreaks the loading of said graph template file.

Poking a bit further...

**Comment by juliusv** [comment]
@mingfang Could you take a look if https://github.com/prometheus/promdash/pull/438 fixes your problem?

**Comment by mingfang** [comment]
It’s still not working for me.

I’m getting 404s on stylesheets/application.css  and javascripts/base.js.

**Comment by juliusv** [comment]
@mingfang Hmm, that's strange. How are you running PromDash (Docker, non-Docker, development or production Rails env?).

I just tested my PR branch from a completely clean checkout and in an incognito browser window, and everything loads correctly (with `PROMDASH_PATH_PREFIX=/prefix`).

**Comment by juliusv** [comment]
I did:

```
git clone git@github.com:prometheus/promdash
git checkout origin/fix-path-prefix
bundle
bundle exec rake db:migrate
DATABASE_URL="<my-db-url>" PROMDASH_PATH_PREFIX=/prefix bundle exec rails s
```

**Comment by mingfang** [comment]
I’m running it using my own Dockerfile.

Please see lines 31-36 here 
https://github.com/mingfang/docker-prometheus/blob/master/Dockerfile

The Runit script is here
https://github.com/mingfang/docker-prometheus/blob/master/sv/promdash/run

I’m going to try your method to see if that works.

**Comment by juliusv** [comment]
That'd be great. I tried the Dockerfile, but it needs the external files that are `ADD`-ed.

Maybe the difference in what we see is because of development vs. production environments, as one compiles assets on-the-fly vs. using precompiled assets.

**Comment by mingfang** [comment]
Everything should be in there.
You have to clone the entire repo.

I provided a convient ```./build``` script and a ```./run``` script.

**Comment by juliusv** [comment]
Thanks! I actually reproduced the problem without the Dockerfile now by just running PromDash's `make build` step and then running it in production mode (`RAILS_ENV="production" GEM_HOME="vendor/bundle" ...`). So indeed it just doesn't work when assets are precompiled. Haven't dug into why yet.

**Comment by juliusv** [comment]
FYI: I'll be on vacation/semi-offline until next week, but @quinox said he might take another stab at this. If not, I'll try to get back to this then. Perhaps I could suggest as a temporary workaround to run PromDash without precompiled assets (like in RAILS_ENV="development" mode) when using a path prefix for now, until this is fixed...

**Comment by mingfang** [comment]
Thanks for working on this. I will use the  suggested the workaround for now.

**Comment by eoghanino** [comment]
+1

**Comment by kvz** [comment]
Just ran into this. The workaround `RAILS_ENV="development" fixed it it for me too

**Comment by grobie** [comment]
In production mode, the assets get pre-compiled before the server gets started usually. This is just guessing, but did you set the `PROMDASH_PATH_PREFIX=...` variable when you executed `make build`? Otherwise the assets get compiled without the prefix and we embed quite a few paths in the assets directly AFAIK.

**Comment by afermon** [comment]
I had the same Issue running a reverse proxy with nginx on ubuntu. In fact @grobie is right. I set   PROMDASH_PATH_PREFIX and RAILS_ENV after building the assets. So I recompiled the assets with rake, restarted the server and it is working now. Thanks!

**Comment by nicholascapo** [comment]
I am running into this problem as well.
I'm running the docker container, as specified in the Readme:

```
docker run --rm -p 3000:3000 \
  -v /var/lib/prometheus:/var/lib/prometheus 
  -e DATABASE_URL=sqlite3:/var/lib/prometheus \
  -e PROMDASH_PATH_PREFIX=/dash
  prom/promdash
```

Then I'm using NGINX as a reverse proxy.
But the app requests `/stylesheets/application.css` and `javascripts/base.js` both of which fail.

**Comment by chance-an** [comment]
This should by design. @grobie 's hypothesis is correct.

This is what works for me:

```
export RAILS_ENV=production
export DATABASE_URL=[YOUR SETTING]
export PROMDASH_PATH_PREFIX=/promdash

rake assets:precompile
```

**Comment by turb** [comment]
As mentioned in the doc PR, a workaround is to set `PROMDASH_PATH_PREFIX`  **and** `RAILS_RELATIVE_URL_ROOT`.
